export const apiEndpoint = 'https://graphigo.prd.dlive.tv'
export const webSocketEndpoint = 'wss://graphigostream.prd.dlive.tv'
export const apiKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRsaXZlLWJ3eGdsd3N5YmciLCJkaXNwbGF5bmFtZSI6Ik1hc2t5X2JvdCIsImF2YXRhciI6Imh0dHBzOi8vaW1hZ2VzLnByZC5kbGl2ZWNkbi5jb20vYXZhdGFyLzQ1MTYxZGE3LTZlNmItMTFlOS1hMWZhLWI2OGRlOTlmODk1YiIsInBhcnRuZXJfc3RhdHVzX3N0cmluZyI6Ik5PTkUiLCJpZCI6IiIsImxpZCI6MCwidHlwZSI6ImVtYWlsIiwicm9sZSI6Ik5vbmUiLCJvYXV0aF9hcHBpZCI6IiIsImV4cCI6MTU3MzQ5NjM0NCwiaWF0IjoxNTcwODE3OTQ0LCJpc3MiOiJETGl2ZSJ9.4Bh6GhK_TbOW_ZJzorKgwFSyFjFny427ACODl4pBglg'
export const commandsList = 'https://pastebin.com/NsEkm8NB'
